config/routes.rb
Moviesite::Application.routes.draw do
  resources :carts do
    resources :lineitems
  end

  resources :orders

  resources :lineitems

  get "shop/index"

  resources :companies

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/story"

  get "pages/top"

  resources :products

  resources :actors

  resources :staffs

  resources :customers
  
  resources :sessions
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  resources :admins

  resources :news_updates

  root :to => 'pages#top'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password
	validates :name, uniqueness: true, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :lineitems, :dependent => :destroy

  def addProduct(product, cart)
    current_item = lineitems.find_by_product_id(product.id)
    if current_item
      current_item.quantity = current_item.quantity + 1
    else
      current_item = cart.lineitems.create(product: product)
      current_item.quantity = 1
    end
    current_item
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password
	validates_confirmation_of :password
	validates_uniqueness_of :name
	validates_uniqueness_of :email
	validates_presence_of :name
	validate :invalid_email
	def invalid_email
		unless email.include?("@")
			errors.add(:email, "Invalid email")
		end
	end
	has_many :orders
	mount_uploader :photo, PhotoUploader
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :order
  belongs_to :product


end

app/models/news_update.rb
class NewsUpdate < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :lineitems
  has_many :products, :through => :lineitems

  def add_lineitems_from_cart(cart)
    cart.lineitems.each do |item|
      item.cart_id = nil
      lineitems << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :lineitems
  has_many :orders, :through => :lineitems

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :customer, :foreign_key => :poster
	validates :title, presence: true
	validates :body, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customers }
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    @customer = Customer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/new
  # GET /customers/new.json
  def new
    @customer = Customer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer }
    end
  end

  # GET /customers/1/edit
  def edit
    @customer = Customer.find(params[:id])
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(params[:customer])

    respond_to do |format|
      if @customer.save 
		Blogmailer.email_to(@customer)
		format.html { redirect_to @customer, notice: 'Thank you. Please check your email.' }
        format.json { render json: @customer, status: :created, location: @customer }
      else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customers/1
  # PUT /customers/1.json
  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update_attributes(params[:customer])
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="sUf">
	<div class="field">
		Photo <%= f.label :photo if @customer.photo? %><br />
		<%= f.file_field :photo %>
	</div>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
    <div class="field">
      <%= f.label :address %><br />
      <%= f.text_area(:address, :size => '31x4' ) %>
    </div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
    <div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Register" %>
	</div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customers.each do |customer| %>
  <tr>
    <td><%= customer.name %></td>
    <td><%= link_to 'Show', customer %></td>
    <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
    <td><%= link_to 'Destroy', customer, 'data-method' => :delete, :class => "delete", :confirm => "Are you sure ?" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<div id="sU_wrap">
	<div class="all_content">
		<table class="forms">
            <tr>
              <td><h1>Sign Up</h1></td>
            </tr>
			<tr>
				<td><%= render 'form' %></td>
			</tr>
		</table>
	</div>
</div>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<div id="cu-wrap">
	<div id="profile">
      <p>
        <%= image_tag(@customer.photo, :alt => "photo") %>
      </p>

      <h3>Name</h3>
      <p>
        <%= @customer.name %>
      </p>

      <h3>Email</h3>
      <p>
         <%= @customer.email %>
      </p>

      <h3>Your Orders</h3>
      <table id="customer_orders_table">
        <% if !@customer.orders.nil? %>
            <% @customer.orders.each do |o| %>
                <tr>
                  <td>Order no <%= o.id %></td>
                  <td><%= euro(o.total) %></td>
                </tr>
            <% end %>
        <% else %>
            <tr>
              <td>You have no orders</td>
            </tr>
        <% end %>
        <table>

      <p><%= link_to 'Update your Profile', edit_customer_path(@customer) %> </p>
	</div>
</div>