config/routes.rb
Moviesite::Application.routes.draw do
  resources :carts do
    resources :lineitems
  end

  resources :orders

  resources :lineitems

  get "shop/index"

  resources :companies

  get "sessions/new"

  get "sessions/create"

  get "sessions/destroy"

  get "pages/story"

  get "pages/top"

  resources :products

  resources :actors

  resources :staffs

  resources :customers
  
  resources :sessions
	match '/signin', :to => 'sessions#new'
	match '/signout', :to => 'sessions#destroy'

  resources :admins

  resources :news_updates

  root :to => 'pages#top'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password
	validates :name, uniqueness: true, presence: true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :lineitems, :dependent => :destroy

  def addProduct(product, cart)
    current_item = lineitems.find_by_product_id(product.id)
    if current_item
      current_item.quantity = current_item.quantity + 1
    else
      current_item = cart.lineitems.create(product: product)
      current_item.quantity = 1
    end
    current_item
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password
	validates_confirmation_of :password
	validates_uniqueness_of :name
	validates_uniqueness_of :email
	validates_presence_of :name
	validate :invalid_email
	def invalid_email
		unless email.include?("@")
			errors.add(:email, "Invalid email")
		end
	end
	has_many :orders
	mount_uploader :photo, PhotoUploader
end

app/models/lineitem.rb
class Lineitem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :order
  belongs_to :product


end

app/models/news_update.rb
class NewsUpdate < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :lineitems
  has_many :products, :through => :lineitems

  def add_lineitems_from_cart(cart)
    cart.lineitems.each do |item|
      item.cart_id = nil
      lineitems << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :lineitems
  has_many :orders, :through => :lineitems

end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :customer, :foreign_key => :poster
	validates :title, presence: true
	validates :body, presence: true
end

app/models/staff.rb
class Staff < ActiveRecord::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies
  # GET /companies.json
  def index
    if params[:search].present?
      @companies = company.near(params[:search], 50, :order => :distance)
    else
      @companies = Company.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @company }
    end

  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
    @company = Company.find(params[:id])
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(params[:company])

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /companies/1
  # PUT /companies/1.json
  def update
    @company = Company.find(params[:id])

    respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing companies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.address %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div id="map_wrap">
    <div style="text-align: center;">
      <h1><%=@company.name %> on the map</h1>
      <div id="maps">
        <%= image_tag "http://maps.google.com/maps/api/staticmap?size=900x800&sensor=false&zoom=16&markers=#{@company.latitude}%2C#{@company.longitude}" %>
      </div>
      <h2>Address</h2>
      <h3><%= @company.address %></h3>
    </div>
</div>